create table
  StravaTokens (
    token_id int not null auto_increment primary key,
    access_token varchar(100) not null,
    expires_at int not null,
    refresh_token varchar(100) not null,
    created_at timestamp not null default now ()
  );

create table
  Activities (
    `id` bigint not null primary key,
    `external_id` varchar(200),
    `resource_state` tinyint,
    `athlete_id` bigint,
    `name` varchar(500),
    `distance` float,
    `moving_time` int,
    `elapsed_time` int,
    `total_elevation_gain` float,
    `sport_type` varchar(100),
    `workout_type` int,
    `start_lat` float,
    `start_lng` float,
    `end_lat` float,
    `end_lng` float,
    `start_date` timestamp,
    `start_date_local` timestamp,
    `timezone` varchar(100),
    `utc_offset` int,
    `location_city` varchar(100),
    `location_state` varchar(100),
    `location_country` varchar(100),
    `achievement_count` int,
    `kudos_count` int,
    `comment_count` int,
    `athlete_count` int,
    `photo_count` int,
    `trainer` boolean,
    `commute` boolean,
    `manual` boolean,
    `private` boolean,
    `visibility` varchar(100),
    `flagged` boolean,
    `gear_id` varchar(100),
    `average_speed` float,
    `max_speed` float,
    `average_cadence` float,
    `has_heartrate` boolean,
    `average_heartrate` float,
    `max_heartrate` float,
    `heartrate_opt_out` boolean,
    `elev_high` float,
    `elev_low` float,
    `upload_id` bigint,
    `upload_id_str` varchar(100),
    `from_accepted_tag` boolean,
    `pr_count` int,
    `total_photo_count` int,
    `has_kudoed` boolean
  );